### ISSUE TITLE
Changing a repository's visibility

### ISSUE THREAD

**Issue by tutipaysudan** [tutipay/java-sdk#20]
It's necessary to restrict our Github repos access (from public to private) until due diligence and risk assessment is completed. 

 
Here are some reference articles that highlights those risks
https://spectralops.io/blog/8-top-git-security-issues-what-to-do-about-them/

Recommendation for our future open source contents;
https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/
https://github.com/ossf/scorecard-action#authentication

**Comment by adonese** [comment]
Hi Sam,
Tuti sdk will be used by clients and partners to implement checkout and
tuti specific functionalities into their apps. Pretty much stripe for ebs,
https://github.com/stripe/stripe-android

We are really getting there in terms of functionalities as now we have
migrated all of our existing internal functionalities to use our sdk
exclusively rather than the previously old system. We only have the UI
components to build before the first payment sdk is fully released and
ready to use at large.
