### ISSUE TITLE
erroneous parameter given to OnError callable

### ISSUE THREAD

**Issue by rami3sam** [tutipay/java-sdk#24]
https://github.com/tutipay/java-sdk/blob/a57f5c04d2f9628779b3710099f29557cb4b8936/lib/src/main/java/com/tuti/api/TutiApiClient.java#L389

this gives java.lang.ClassCastException because the two parameters given are of Exception type i think the first one should be of type TutiResponse

**Comment by adonese** [comment]
Ok, i checked this, but let me write down what i think this is for, and you help me explain why that might be incorrect:
- we have three cases we make a callable, one for non-EBS errors (400s, etc)
- we have ebs errors, which generally are marshalled onto TutiResponse 
- And the last bit there is for the `other` cases, it catches all the exceptions including network exceptions (noebs or EBS is down and so on)

In the client code, since it has been a while for me, how does the last case affect you. Please confirm:
- that my notes above are correct, i just want to make sure i am on the same page with you
- and, what are the intended use case that you want to implement. Also, i remember, previously we used to catch all types of errors, but i changed that to only capture network error. And java only has a IOException class for that
